module.exports = {
  FETCHED_ALL_NOTEBOOKS: 'FETCHED_ALL_NOTEBOOKS',
  FETCHED_SINGLE_NOTEBOOK: 'FETCHED_SINGLE_NOTEBOOK',
  CREATED_NOTEBOOK: 'CREATED_NOTEBOOK',
  SAVED_NOTEBOOK: 'SAVED_NOTEBOOK',
  DELETED_NOTEBOOK: 'DELETED_NOTEBOOK'
};
