module.exports = {
  FETCHED_ALL_NOTES: 'FETCHED_ALL_NOTES',
  FETCHED_SINGLE_NOTE: 'FETCHED_SINGLE_NOTE',
  CREATED_NOTE: 'CREATED_NOTE',
  SAVED_NOTE: 'SAVED NOTE',
  DELETED_NOTE: 'DELETED_NOTE'
};
